### ISSUE TITLE
Geophilic Leaves Texture Bug Fabric 1.21

### ISSUE THREAD

**Issue by ZealousVult2283** [everloste/my-mc-projects#5]
Geophilic, Mod in 1.21 Fabric Minecraft

When using the mod, the leaves revert to the old, programmer art style textures without me putting on the programmer art.

![image](https://github.com/user-attachments/assets/50797191-f99f-4da2-8dde-90a5a00ade25)

I did check and it is Geophilic

**Comment by everloste** [comment]
i'm sorry but there's just no way for that to happen, can't be a geophilic issue
