### ISSUE TITLE
Structures Not Spawning 

### ISSUE THREAD

**Issue by OJayyusiO** [everloste/my-mc-projects#8]
**Mod and game version**
Fabric 1.20.1, mod version 1.6.2

**Describe the bug**
Structures not spawning even when using /locate 

**Screenshots (optional)**
![image](https://github.com/user-attachments/assets/d83fc5a0-163c-44fb-8f35-75c565b34cd4)

**Additional context (optional)**
Is it a mod compatibility issue or could it possibly be an issue in setting up the server since i generated this world on a server

Thank you!

**Comment by everloste** [comment]
according to your chat log, you searched for the biomes they would spawn in, not for the structures themselves. the structures should be generating fine. make sure to use `/locate structure`
