### ISSUE TITLE
Bone meal doesn't grow flowers as it should.

### ISSUE THREAD

**Issue by PavelDobCZ23** [everloste/my-mc-projects#9]
**Mod and game version**
Minecraft - 1.21 Fabric - 0.16.5 Geophilic - 3.1.1

**Describe the bug**
When using bone meal in some biomes, the flowers that grow don't correspond to the flower distribution table, which you can find at [minecraft wiki](https://minecraft.wiki/w/Flower#Flower_biomes). For example, in Jungles, Savannahs, Birch Forests, Forests, Dark Forests or Deserts no flowers grow from bone meal at all. It affects the "Any Other" and "Forest" category from the table the most, it seems.

**To reproduce (optional)**
1. Go to a biome, where flowers should grow from bone meal-ing grass.
2. Try bone meal-ing empty grass blocks.
3. Observe flowers missing. (Use the table linked above to check which flowers should get produced.)

**Screenshots (optional)**
None

**Additional Context (optional)**
I believe it has something to do with the fact, that the configured features of flowers like "forest" or "classic" do not have the feature type of "minecraft:flower", as the Bone Meal logic in Minecraft's code uses that to determine, which flowers to place when using bone meal on grass blocks.

**Comment by everloste** [comment]
you're right, that's an oversight, the classic flowers feature should be of the flower type. do note though, forest flowers do not use the flower feature type in vanilla either, so that is intentional.

**Comment by PavelDobCZ23** [comment]
> you're right, that's an oversight, the classic flowers feature should be of the flower type. do note though, forest flowers do not use the flower feature type in vanilla either, so that is intentional.

I've fixed it locally for myself already with good results, it's really just about changing some "minecraft:random_patch" types to "minecraft:flower", shouldn't be anything problematic.

**Comment by everloste** [comment]
i know :) fixed in v3.1.3.
